idf_component_register(SRCS "main.c"
                            "tof_hcsr04.c"
                            "neo_strip.c"
                            "anim.c"
                            "sensor_test.c"
                            "strip_test.c"
                            "rfid_mfrc522.c"
                    INCLUDE_DIRS ".")
